### ISSUE TITLE
Working with a tibble

### ISSUE THREAD

**Issue by elinw** [jbryer/likert#102]
This isn't really a bug per se but I had a data set read in from an spss sav file using haven, which made it a tibble.  Although I explicitly converted the characters to ordered factors with the same levels, I was getting the not all variables have the same levels message.  When I coerced to a data frame it worked as expected.

Thanks for this package!

**Comment by jbryer** [comment]
The likert function will convert a tibble to a data.frame. In the vast majority of cases this will solve the issue. I do not want to include tibbles (or tidyvserse) as a dependency so this is the best solution at the moment. Google "trouble with tibbles" to understand why this is an issue.
