### ISSUE TITLE
Misplaced sections in right side of the plot when using grouping 

### ISSUE THREAD

**Issue by mcortes-lopez** [jbryer/likert#111]
Hi, 
I have been having the same problem when I use grouping, my categories in the right side of the panel get changed of place and it looks like this 
![image](https://user-images.githubusercontent.com/34006345/74259027-829a3a00-4cf7-11ea-8a73-c93f15a26687.png)

or 
![image](https://user-images.githubusercontent.com/34006345/74259095-9fcf0880-4cf7-11ea-84ac-0da27e3d09f3.png)

How can I get the plot in the right order?

**Comment by jbryer** [comment]
Can you provide a small example using the pisaitems dataset included in the
package?

**Comment by mcortes-lopez** [comment]
Ok, I found the problem, I had an older version installed.
