### ISSUE TITLE
Missing Link ... 

### ISSUE THREAD

**Issue by NMarkgraf** [jbryer/likert#121]
Well, on the this page it is written: "More information can be obtained at http://jason.bryer.org/likert." but the url seems no longer be valid!

**Comment by NMarkgraf** [comment]
Nice, no answer but just closing the issue! 

The error is still that  "More information can be obtained at http://jason.bryer.org/likert. " has a wrong link! It should be: " More information can be obtained at https://jason.bryer.org/likert.". Sometimes a "s" is important!

**Comment by jbryer** [comment]
There were two links, one was fixed. 

In the future, you can alert maintainers (who are volunteers) that there is still an issue without snark. Your tone is not helpful.

**Comment by NMarkgraf** [comment]
Well, my apologies to you. - But I am just an interested user trying to find a litte help and ran into difficulties with a link. I am unpaid for this too, but not fixing this and closing an issue without dropping a line is also not helpful.

In addition: on new page (which is sadly nearly the old staring page) the Get Started and Reference links will lead to  "page not found" scenarios. Which is also not very helpful. -- But I think you are not interested in such a remark, so thanks for your work, which is a great help for me.
