### ISSUE TITLE
Problem with plot.percents

### ISSUE THREAD

**Issue by mauriziopassariello** [jbryer/likert#132]
Hi,
I have successfully plotted a survey with the likert package with this code:

plot(ResultPSrev, wrap=15, text.size=2.7,
     group.order = c("Statement 1", "Statement 2", "Statement 3", "Statement 4", "Statement 5", "Statement 6", "Statement 7"),
     type="bar")

However, when I add plot.percents=TRUE I get the following error: 

Error in ddply(results[results$value > 0, ], .(Item), transform, pos = cumsum(value) -  : 
  could not find function "ddply"

How can I show the percentages in the stacked bar?

**Comment by mauriziopassariello** [comment]
PS: I have looked at the issue #130 but in my case there are no groupings.

I would very much appreciate any help from anyone that knows what the problem may be and can fix my code.

**Comment by kidwellj** [comment]
I've just hit this issue as well. I think the underlying problem is that ddply can be masked by other libraries. See here: Lhttps://github.com/jbryer/likert/issues/114
