### ISSUE TITLE
too much overlay when plot.percents = T and factor levels are odd number

### ISSUE THREAD

**Issue by gie-de-moo** [jbryer/likert#14]
Centered level's percent is displayed twice, once as a sum and once split into 2 parts, when plot.percents = T and factor levels are odd numbers. 

plot(l29, plot.percents = T) + ggtitle(title) 
rendered the plot below. 
![image](https://f.cloud.github.com/assets/5746784/1381011/b8ab6622-3b16-11e3-98a0-5aefc025d308.png)

plot(l29, plot.percents = T, plot.percent.neutral= F) + ggtitle(title)
gives
![image](https://f.cloud.github.com/assets/5746784/1381015/d60e2038-3b16-11e3-9c21-92725932434e.png)

I think maybe it is better if only the total percent of centered level is displayed.  Probably it is not a big problem , since one can always set plot.percents = F and add a geom_text layer separately to fix this. 

Thank you for the great package!

**Comment by mine-cetinkaya-rundel** [comment]
Any plans on updating this? I agree that it would be better when `plot.percents = TRUE` to only show the total percent of centered level (or add an option to do so).
