### ISSUE TITLE
Error in sum(x) : invalid 'type' (character) of argument

### ISSUE THREAD

**Issue by ericpgreen** [jbryer/likert#26]
I was getting this error when trying to use `grouping`, so I tried the sample code: `l28g <- likert(items28, grouping = pisaitems$CNT)`. Got the same error. Happening for anyone else?

**Comment by mtorchiano** [comment]
confirm the same issue and @gd047 solution

**Comment by unikum** [comment]
Traceback for the  error call:

```R
> traceback()
11: FUN(newX[, i], ...)
10: apply(t, 2, FUN = function(x) {
        x/sum(x) * 100
    })
9: likert(., grouping = data_tbl$Пол)
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(expr, envir, enclos)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: data_tbl %>% select(contains("Q25.")) %>% mutate_each(funs(as.factor)) %>% 
       as.data.frame %>% likert(grouping = data_tbl$Sex)
```

**Comment by Telofy** [comment]
Confirmed, and thanks, @gd047, for the workaround.

**Comment by Mababyak** [comment]
Loaded reshape, reinstalled likert from github, but still a merge error when using grouping. From the demo on the likert page, everything works till I get here:

    > l24g <- likert(items24, grouping=pisaitems$CNT)
    Error in fix.by(by.y, y) : 'by' must specify uniquely valid columns
    > 
    > traceback()
    5: stop(ngettext(sum(bad), "'by' must specify a uniquely valid column", 
           "'by' must specify uniquely valid columns"), domain = NA)
    4: fix.by(by.y, y)
    3: merge.data.frame(results, t, by.x = c("Group", "Response"), by.y = c("Var2", 
           "Var1"), all.x = TRUE)
    2: merge(results, t, by.x = c("Group", "Response"), by.y = c("Var2", 
           "Var1"), all.x = TRUE)
    1: likert(items24, grouping = pisaitems$CNT)
