### ISSUE TITLE
"Percentage" hardcoded in barplot

### ISSUE THREAD

**Issue by bonndan** [jbryer/likert#28]
The barplot function uses the word "Percentage" as legend description in the source. This does not fit nicely when plotting scales with foreign levels.

Perhaps you can introduce an "yLab" param?

**Comment by WashingtonSilva** [comment]
I have the same need. How can we translate "Percentage" and "Responde"? Thanks

**Comment by WashingtonSilva** [comment]
plot(items) + guides(fill = guide_legend(title = "Translated")) + labs(y = "Translated")

Works fine for me.
