### ISSUE TITLE
Output error integrating with tikzDevice package

### ISSUE THREAD

**Issue by lightonphiri** [jbryer/likert#29]
I run into errors when I attempt to output my divergent stacked bar to native TeX code using tikZDevice package. I get the impression it has something to do with the % sign in the resulting graph.

Error I get is below and code and data I am working with is here [1]

[1] https://gist.github.com/phiri/936acb5a12d3b5721c10

Error log

File: epstopdf-sys.cfg 2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Liv
e
))
Preview: Fontsize 10pt
Preview: PDFoutput 1
! Undefined control sequence.
l.19 \path
           let \p1 = ($(TeX.east) - (TeX.west)$), 
Here is how much of TeX's memory you used:
 11606 strings out of 493308
 234511 string characters out of 6137822
 262787 words of memory out of 5000000
 14865 multiletter control sequences out of 15000+600000
 4403 words of font info for 15 fonts, out of 8000000 for 9000
 957 hyphenation exceptions out of 8191
 55i,3n,54p,416b,485s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
Error in getMetricsFromLatex(TeXMetrics) : 
TeX was unable to calculate metrics for the following string
or character:

```
    12%
```

Common reasons for failure include:
- The string contains a character which is special to LaTeX unless
  escaped properly, such as % or $.
- The string makes use of LaTeX commands provided by a package and
  the tikzDevice was not told to load the package.

The contents of the LaTeX log of the aborted run have been printed above,
it may contain additional details as to why the metric calculation failed.
Calls: <Anonymous> ... tryCatchList -> evalFunc -> print -> print.likert.bar.plot
Execution halted

**Comment by KimAlessandro** [comment]
This task is solved by tikzdevice. Once can use the option sanitize=TRUE as mentioned in the documentation for plots you don't have full access. This work for me.
