### ISSUE TITLE
Bug in likert.bar.plot when 'ordered = TRUE'

### ISSUE THREAD

**Issue by mlu68** [jbryer/likert#31]
Hi,

I'm trying to plot a centered Likert scale.
When summarizing the Likert object with ordered = TRUE, it looks all good:
![image](https://cloud.githubusercontent.com/assets/7920434/3310708/8f8065c2-f6b9-11e3-8f01-d9b9f738a8b8.png)
However, when plotting this object, the order is not respected:
![image](https://cloud.githubusercontent.com/assets/7920434/3310713/b1364650-f6b9-11e3-92b1-e8582dc6e365.png)
As you can see, 'Protocoles' is not on the top of the plot. Seems like the plot is sorted according to alphabetical order...
Any help would be much appreciated !
Thanks in advance,

MLU

**Comment by jbryer** [comment]
I believe this has been fixed. If not, please provide a reproducible example.

**Comment by mlu68** [comment]
Thank you.
I'm going to test this and let you know if I encounter the issue again.
Best,

<http://www.octo.com/>
Michel *Lutz*

*OCTO Technology*
Consultant

.....................................................

50, Avenue des Champs-Elysées

75008 Paris

+33 (0)6 13 26 78 56

+33 (0)1 58 56 10 10

www.octo.com - blog.octo.com
www.usievents.com

.....................................................

2015-11-12 17:55 GMT+01:00 Jason Bryer <notifications@github.com>:
