### ISSUE TITLE
Warning when installing the package

### ISSUE THREAD

**Issue by mquinson** [jbryer/likert#36]
When I follow the procedure given in README file, ie:

```
require(devtools)
install_github('likert', 'jbryer')
```

then I get the following error message:
```Username parameter is deprecated. Please use jbryer/likert```

I guess that the README file should be updated or I'm missing something?

**Comment by svenski** [comment]
mquinson: It's a messge from the devtools package asking you to use `install_github("jbryer/likert")` instead of the call you are making.

**Comment by mquinson** [comment]
Thanks for the workaround. As I was just copy/pasting the code from the README, I can only reiterate my advice to update that README, please.

Thanks for the great software,
