### ISSUE TITLE
Wrong Order in Histogram

### ISSUE THREAD

**Issue by Telofy** [jbryer/likert#40]
This is probably related to #33 and maybe to #21 and #31. I’m not quite sure though, so I’d rather create a new issue for it.

I’ll use [the tutorial](http://jason.bryer.org/likert/) as example. In the tutorial we do:

    > l28g <- likert(items28, grouping=pisaitems$CNT)
    > plot(l28g, include.histogram=TRUE)

![rplot](http://jason.bryer.org/images/likert/centeredPlot2.png)

This works as expected. However I think it is coincidental that the histogram is plotted correctly, because if I rename “United States” to “Australia,” the histogram bars get mixed up. It seems they’re always sorted in reverse alphabetical order.

    > levels(pisaitems$CNT)[levels(pisaitems$CNT) == 'United States'] <- 'Australia'
    > l28g <- likert(items28, grouping=pisaitems$CNT)
    > plot(l28g, include.histogram=TRUE)

![rplot](https://cloud.githubusercontent.com/assets/223663/8391459/0324e322-1cc5-11e5-9c20-5eab07674128.png)

    > summary(pisaitems$CNT)
       Canada    Mexico Australia 
        23207     38250      5233 

[Marforic’s workaround](https://github.com/jbryer/likert/issues/33#issuecomment-57628037) works for me also in this context, which makes me think the problems are probably related.

    > plot(l28g, include.histogram=TRUE, group.order=c('Australia', 'Mexico', 'Canada'))

![rplot01](https://cloud.githubusercontent.com/assets/223663/8391484/8fd0ff9a-1cc5-11e5-885b-252243a8342e.png)

Thanks!

**Comment by jbryer** [comment]
Thanks. This is fixed in the latest version on Github.
