### ISSUE TITLE
Likert and Knitr rendering problems

### ISSUE THREAD

**Issue by bganicky** [jbryer/likert#43]
Hi,

I've come upon some issues when trying to render Likert bar plots via Knitr.
1. `wrap` attribute has no effect in Knitr rendered document
2. grouped plots are squeezed and unreadable when rendered via Knitr: [normal](http://i.imgur.com/5tefLbm.png), [knitr](http://i.imgur.com/Kt6D6iO.png)

When doing the same Likert calls in RStudio console, everything is just fine and works as expected. See screenshots above.

Are these known and hopefully fixable issues? Thank you!

**Comment by jbryer** [comment]
@bganicky I'm not seeing the screenshots. Can you provide a reproducible example? We use this in Sweave and markdown all the time without issues.
