### ISSUE TITLE
Grouping: example not working?

### ISSUE THREAD

**Issue by alexperrone** [jbryer/likert#44]
I pasted the example without modification directly from the documentation currently at http://jason.bryer.org/likert/index.html

The grouping yields an error shown below. 

    library(likert)
    data(pisaitems)
    items29 <- pisaitems[, substr(names(pisaitems), 1, 5) == "ST25Q"]
    names(items29) <- c("Magazines", "Comic books", "Fiction", "Non-fiction books", "Newspapers")
    l29g <- likert(items29, grouping = pisaitems$CNT)  # error
    ## Error in sum(x) : invalid 'type' (character) of argument
    l29g <- likert(items29, grouping = factor(pisaitems$CNT))  # same error
    
    
    sessionInfo()
    ## R version 3.2.1 (2015-06-18)
    ## Platform: x86_64-apple-darwin13.4.0 (64-bit)
    ## Running under: OS X 10.9.5 (Mavericks)
    ## 
    ## locale:
    ##   [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
    ## 
    ## attached base packages:
    ##   [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ##   [1] testthat_0.10.0  lubridate_1.3.3  readr_0.1.1      reshape2_1.4.1   magrittr_1.5     data.table_1.9.4 plyr_1.8.3      
    ## [8] knitr_1.11       likert_1.2       xtable_1.7-4     ggplot2_1.0.1   
    ## 
    ## loaded via a namespace (and not attached):
    ##   [1] Rcpp_0.12.1      MASS_7.3-43      mnormt_1.5-3     munsell_0.4.2    colorspace_1.2-6 stringr_1.0.0    tools_3.2.1     
    ## [8] parallel_3.2.1   grid_3.2.1       gtable_0.1.2     psych_1.5.8      digest_0.6.8     crayon_1.3.1     gridExtra_2.0.0 
    ## [15] memoise_0.2.1    labeling_0.3     stringi_0.5-5    scales_0.3.0     reshape_0.8.5    chron_2.3-47     proto_0.3-10

**Comment by jbryer** [comment]
This error is caused by having the reshape and reshape2 packages loaded at the same time. Detach the reshape package and it works. I have added a package startup message if we detect that reshape is loaded.
