### ISSUE TITLE
Local paths in repository. 

### ISSUE THREAD

**Issue by filipstachura** [jbryer/likert#46]
Just take a look at server.R code:
https://github.com/jbryer/likert/blob/a36d14352a1d799c35f27a3f30dd0e3cbea5c945/inst/shiny/server.R

```
source('C:/Users/User/Dropbox/Github/likert/R/xtable.likert.R')#rm this when github syncs
```

This is the error I get:

```
likert:::shinyLikert()

Listening on http://127.0.0.1:5240
Warning in file(filename, "r", encoding = encoding) :
  cannot open file 'C:/Users/User/Dropbox/Github/likert/R/xtable.likert.R': No such file or directory
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
```

BTW Even though README.md  tells to try shiny app with `shinyLikert()` this function is not exported globally.

**Comment by jbryer** [comment]
The shiny app may be included in a future version.
