### ISSUE TITLE
levels in bar plot are not mapped correctly, if not all levels have data and if grouping is used

### ISSUE THREAD

**Issue by andreaphsz** [jbryer/likert#50]
It is easier to explain the serious(!) errror by an example:

```
df <- data.frame(g=c(1,1,1,2,2,2), x=c(2,3,3,2,3,3), y=c(2,3,3,1,3,3))

df$g <- factor(df$g)
df$x <- factor(df$x, levels=1:3)
df$y <- factor(df$y, levels=1:3)

li <- likert(df[,2:3], grouping=df$g, nlevels=3)
plot(li)
```

The two bars in the upper half of the plot (x) should look similar as the upper bar in the lower half of the plot (y).
![bug](https://cloud.githubusercontent.com/assets/3206936/12300796/56229204-ba1d-11e5-9528-765333cddaab.png)

**Comment by jimdholland** [comment]
Yeah, I just came across this as well.

    require(likert)

    mylevels <- c('Strongly Disagree', 'Disagree', 'Neither', 'Agree', 'Strongly Agree')

    # Create with only positive responding
    items <- data.frame('Item 1'=factor(sample(mylevels[4:5], 100, replace=TRUE)),
					'Item 2'=factor(sample(mylevels[3:5], 100, replace=TRUE)),
					'Item 3'=factor(sample(mylevels[4:5], 100, replace=TRUE)),
					check.names=FALSE)
    str(items)
    groups <- sample(c('g1','g2'), 100, replace=TRUE)

    # Here we will recode each factor and explicitly set the levels
    for(i in seq_along(items)) {
	items[,i] <- factor(items[,i], levels=mylevels)
    }
    lgood <- likert(items)
    lgood
     # Works fine
    plot(lgood)

![image](https://cloud.githubusercontent.com/assets/7240007/12306363/f5967d9c-b9fe-11e5-84d0-318318e71eae.png)

    # Now break apart by groups
    lgr <- likert(items, grouping=groups)
    summary(lgr)
    plot(lgr)

![image](https://cloud.githubusercontent.com/assets/7240007/12306372/01e26926-b9ff-11e5-8b23-7c8a589422ce.png)

**Comment by jimdholland** [comment]
Hmmm, what's really odd is when I walk the example code above though the likert.R and summary.R code for groups, I cannot replicate the problem.  But if I run the likert() function and then call the summary on it, it miscodes the high responses as low.

**Comment by andreaphsz** [comment]
Until bug is fixed, I use an workaround, i.e. I fix the results table manually!
```
## workaround: fix results table manually
a <- li$results

a[c(1,3),3] <- 0
a[c(1,3),4] <- a[2,4]
a[c(1,3),5] <- a[2,5]

li2 <- likert(summary=a[,2:5], grouping=a[,1], nlevels=3)
plot(li2)
```
<img width="560" alt="bildschirmfoto 2016-01-15 um 10 56 38" src="https://cloud.githubusercontent.com/assets/3206936/12350329/b0e9623a-bb76-11e5-9ce1-45a7d5b7afc6.png">

**Comment by jimdholland** [comment]
What's funny is when I tried finding the bug by walking through the code, I couldn't replicate it.  That said, you can use this function with the relevant parts from the likert.R code.  I've tested on some data and it works, but be warned, I didn't use all the options from the Likert, so double check if you use this for anything seriously.  

    groupFix <- function(mydata, myGroup, levs = 5) {

	items <- mydata
	#items <- ccs[grab("School Leadership - Ass")]

	factors <- NULL
	grouping = myGroup
	
	nlevels <- levs

	lowrange <- 1 : ceiling(nlevels / 2 - nlevels %% 2)
	highrange <- ceiling(nlevels / 2 + 1 ) : nlevels

	results <- data.frame()

	results <- data.frame(
		Group = rep(unique(grouping), each=nlevels),
		Response = rep(1:nlevels, length(unique(grouping)))
		)
	for(i in 1:ncol(items)) {
		t <- as.data.frame(table(grouping, items[,i]))
		t <- reshape2::dcast(t, Var2 ~ grouping, value.var='Freq', add.missing=TRUE)
		t <- cbind(Response=t[,1], 
				   apply(t[,2:ncol(t)], 2, FUN=function(x) { x / sum(x) * 100 } )
		)
		t <- reshape2::melt(t)
		results <- merge(results, t, 
						 by.x=c('Group','Response'), by.y=c('Var2','Var1'), 
						 all.x=TRUE)
		names(results)[ncol(results)] <- paste0('Col', i)
	}

	names(results)[3:ncol(results)] <- names(items)

	results$Response <- factor(results$Response, levels=1:nlevels, 
							  labels=levels(items[,i]))
	results <- reshape2::melt(results, id=c('Group', 'Response'))
	results <- reshape2::dcast(results, Group + variable ~ Response)
	results <- as.data.frame(results)
	names(results)[2] <- 'Item'

	for(i in 3:ncol(results)) {
		narows <- which(is.na(results[,i]))
		if(length(narows) > 0) {
			results[narows, i] <- 0
		}
	}
			
			
	r <- list(results=results, items=items, grouping=grouping, factors=factors,
			  nlevels=nlevels, levels=levels(items[,1]))

	class(r) <- 'likert'
	
	return(r)

    }

    mylevels <- c('Strongly Disagree', 'Disagree', 'Neither', 'Agree', 'Strongly Agree')

    # Create a dummy data frame. Note that "Item 1" has only four levels
     items <- data.frame('Item 1'=factor(sample(mylevels[4:5], 100, replace=TRUE)),
					'Item 2'=factor(sample(mylevels[3:5], 100, replace=TRUE)),
					'Item 3'=factor(sample(mylevels[4:5], 100, replace=TRUE)),
					check.names=FALSE)
    str(items)
    groups <- sample(c('g1','g2'), 100, replace=TRUE)



    # Here we will recode each factor and explicitly set the levels
     for(i in seq_along(items)) {
    	  items[,i] <- factor(items[,i], levels=mylevels)
    }

    myLik <- groupFix(items, myGroup = groups)
    plot(myLik)

    bug <- likert(items, grouping = groups)
    plot(bug)

**Comment by drcanak** [comment]
I too came across this, and could not identify the problem.  It does appear to be a summary issue, as you can tell from the summary results, pre-plot, that something is wrong.

That being said, installing the newest development version seemed to resolve this issue.  In reviewing the repository, it appears as if the author may have corrected the issue sometime around December, 2015.

**Comment by aatishb** [comment]
Wow, this was a huge issue. I just ran into it as well, fortunately the most recent development version fixed it!

**Comment by nuernber** [comment]
@aatishb I just tried the latest dev version via `devtools::install_github('jbryer/likert')` and it didn't work for me. I successfully used @andreaphsz's workaround to get the plot working; thanks!

**Comment by drcanak** [comment]
@nuernber,

you could also perhaps try version 3.14, which is the latest version that did work. Whatever was changed from 1.3.4 to 1.3.5 perhaps broke it again.  Not at all good with github, but this is the relevant bit from December 27th, 2015:

@@ -1,3 +1,8 @@
+likert 1.3.4
+=========
+
+* Fixed a bug where the results for a grouped analysis with missing levels may not be correct in the print function.
+
 likert 1.3.3

That 1.3.4 version was, at one time, the development version referred to earlier.  hth

**Comment by jbryer** [comment]
I believe this has been fixed. I can't tell if this is related to the issues introduced in ggplot2 version 2.2.0. If someone can verify with another example, I would appreciate it.

**Comment by jbryer** [comment]
I do believe this was due to mis-specified factor variables.

**Comment by jbryer** [comment]
Will now print a warning if a variable is not a factor.
