### ISSUE TITLE
Possible to add confidence intervals or test stats for diffs b/w groups?

### ISSUE THREAD

**Issue by jquattro** [jbryer/likert#57]
This package is fantastic! Just wondering if it would be possible to add the ability to indicate if comparisons across groups are statistically significant. For example, in the provided examples looking at reading differences across Mexico, Canada, and the US, would it be possible to show an F statistic and associated p-value in a column to the right?

**Comment by jpaulbrowning** [comment]
Great idea!

**Comment by jbryer** [comment]
This is a complicated issue I am not sure I want to introduce into this package. Added test statistics assumes you can treat the likert responses as continuous variables. In most cases, at least at the item level, I don't think you can. To treat them as continuous variables you are assuming the intervals are equal, and generally they are not. The inclusion of density plots was, in part, a way to check some of those assumptions. However, I do regret having that plot type and may remove it in version 2. See this article for more information: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4833473/
