### ISSUE TITLE
Plot has extra space if values are only in upper half of factor

### ISSUE THREAD

**Issue by harmsk** [jbryer/likert#59]
R version: from github (5c6b0ec4ae5c77b07293727c3ebfabc625052c73)

If you have a factor, and all the values are in the upper half of the factor, then the resulting plot always has extra space above it. See the examples below. I've spent several hours trying to figure out why this happens. But I can't find the bug. Any idea what's going on here?

Extra Space:

``` R
q = factor(c(6, 6, 7, 5, 5, 7, 7), levels = 1:7)
l = likert(data.frame(q))
plot(l)
```

![space](https://cloud.githubusercontent.com/assets/957446/17984825/a3116e0c-6ad8-11e6-9058-cda9bc765f3b.png)

However, this works:

``` R
q = factor(c(1, 6, 7, 5, 5, 7, 7), levels = 1:7)
l = likert(data.frame(q))
plot(l)
```

![no-space](https://cloud.githubusercontent.com/assets/957446/17984845/b4bd5f30-6ad8-11e6-80e9-a1ec1510f665.png)

And so does this.

``` R
q = factor(c(3, 3, 1, 3, 2, 1, 1), levels = 1:7)
l = likert(data.frame(q))
plot(l)
```

![no-space2](https://cloud.githubusercontent.com/assets/957446/17984849/bb2b741a-6ad8-11e6-8c99-a4954137b8f7.png)

**Comment by trineebell** [comment]
Ever find a solution to this? It's driving me insane!
