### ISSUE TITLE
conflicts with tibble classes

### ISSUE THREAD

**Issue by robertmitchellv** [jbryer/likert#62]
I have been racking my brain trying to figure out why my data would not work with the `likert()` function.  I think it has something to do with either class `tbl` or `tbl_df`.

Here's a quick example in a R Notebook:

``` r
library(tidyverse)
library(likert)
```

```
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages -------------------------------------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
Loading required package: xtable

Attaching package: ‘likert’

The following object is masked from ‘package:dplyr’:

    recode
```

``` r
survey <- tribble(
  ~feel_today, ~feel_yesterday, ~feel_last_week,
  "fine",      "poor",          "good",
  "poor",      "fine",          "fine",
  "good",      "good",          "poor",
  "fine",      "poor",          "poor"
)
```

``` r
levels <- c("poor", "fine", "good")
survey <- survey %>% mutate_all(funs(factor(., levels = levels)))
```

``` r
survey
```

``` r
map(survey, class)
```

```
$feel_today
[1] "factor"

$feel_yesterday
[1] "factor"

$feel_last_week
[1] "factor"
```

``` r
map(survey, nlevels)
```

```
$feel_today
[1] 3

$feel_yesterday
[1] 3

$feel_last_week
[1] 3
```

``` r
likert(survey)
```

```
Error in likert(survey) : 
  All items (columns) must have the same number of levels
```

``` r
items <- as.data.frame(survey)
```

``` r
likert(items)
```

```
            Item poor fine good
1     feel_today   25   50   25
2 feel_yesterday   50   25   25
3 feel_last_week   50   25   25
```

I was reading about tibbles this morning and I know there are differences, especially between `[` and `[[` in terms of returning another tibble or a vector.  Not sure what might be going on under the hood but thought you might like to know about it.

Thanks for the package!

**Comment by jcpsantiago** [comment]
Having the same issue it seems:
https://github.com/jbryer/likert/issues/5

likert(as.data.frame(data)) works

**Comment by bdecker** [comment]
@robertmitchellv Thanks so much for this solution. Works well!

**Comment by jbryer** [comment]
Thanks @bdecker. For now this is the solution. I am not sure how to handle tibble classes going forward. It seems to break base R in unpredictable ways.

**Comment by trianglegirl** [comment]
I had the same issue. Thank you for flagging it - I wouldn't have thought of it by myself!
Fixed with as.data.frame(df)

**Comment by Pablo-A-Baeza** [comment]
You solved my issue too! Thanks I was going crazy
