### ISSUE TITLE
How can I change the font size in the likert graph?

### ISSUE THREAD

**Issue by roadfar** [jbryer/likert#66]
Hi,
As with the title, I want to change the font size, but don't find a method in the demo. Should I use the ggplot to realize that? 
Thanks~

**Comment by sinaa** [comment]
You can use text.size to increase the size of the percentages in the plot.

To modify the size of the other labels, you can use ggplot's theming features. 

For instance: `plot(p) + theme(axis.text=element_text(size=12))` increases the size of the grouping labels, etc.

**Comment by roadfar** [comment]
@sinaa Got it~ Thanks a lot!
