### ISSUE TITLE
Facet order reverts to alphabetical in grouped bar plot

### ISSUE THREAD

**Issue by randallgrout** [jbryer/likert#67]
The grouped bar plots displays facet items in alphabetical order, regardless of the order of columns from the original data frame.

Using the demo data:

```
require(likert)
data(pisaitems)

items29 <- pisaitems[,substr(names(pisaitems), 1,5) == 'ST25Q']
names(items29) = c("Magazines", "Comic books", "Fiction", "Non-fiction books", "Newspapers")

l29g <- likert(items29, grouping=pisaitems$CNT)
plot(l29g)
```
![image](https://cloud.githubusercontent.com/assets/22521672/21573241/ffff842e-ceaf-11e6-8287-7008ded2c8cf.png)

I expect the book categories to be listed in the order of the input data: 

`c("Magazines", "Comic books", "Fiction", "Non-fiction books", "Newspapers")`

The factor levels are specified according to the original data frame's column order in the likert object and ggplot data.

```
levels(l29g$results$Item)
[1] "Magazines"         "Comic books"       "Fiction"           "Non-fiction books" "Newspapers" 

a <- plot(l29g)
levels(a$data$Item)
[1] "Magazines"         "Comic books"       "Fiction"           "Non-fiction books" "Newspapers"       

b <- print(l29g)
levels(b$Item)
[1] "Magazines"         "Comic books"       "Fiction"           "Non-fiction books" "Newspapers"    
```

Interestingly, the summary method for the likert object has the item levels in alphabetical order.

```
c <- summary(l29g)
levels(c$Item)
[1] "Comic books"       "Fiction"           "Magazines"         "Newspapers"        "Non-fiction books"
```

I suspect this is due to the method used by summary to create the data frame, as seen at https://github.com/jbryer/likert/blob/master/R/summary.likert.r#L94.  However, if I change line 95 (https://github.com/jbryer/likert/blob/master/R/summary.likert.r#L95) to

` Item=factor(rep(names(items), length(unique(results$Group))), levels = names(object$items)),`

the summary items are in the correct order, but the plot remains as above.

```
c <- summary(l29g)
levels(c$Item)
[1] "Magazines"         "Comic books"       "Fiction"           "Non-fiction books" "Newspapers"  
```

The facet_* function from ggplot2 does not appear to accept functions, so I'm not able specify the generated plot's facets.  At most I can reverse the order with: 

`facet_wrap(~ Item, ncol=1, as.table = FALSE)`

Is there a way to have the faceted items respect the order of columns or factors in the input dataframes?

**Comment by petestmarie** [comment]
Hi Jason,
Wondering if there's an update on this bug?
Thanks

**Comment by SarBearSchwartz** [comment]
I am having this same issue with the facet's reverting to alphabetic order in grouped likert plots.  Was this fixed back in 2017?

**Comment by JakeC007** [comment]
Is there any update on this?

**Comment by layka-pacheco** [comment]
Hej :)

Is there any solution here? I have been having the very same issue. I can also reverse the order, but not really control it. Please send help.

Best, George.

**Comment by olizardo** [comment]
I found a solution that worked for me. 

1) create a likert object from your data.

mylikert <- likert(mydata, grouping = mydata$group)

2) Plot it

myplot <- plot(mylikert)

3) And this is the main step, *relevel the factor that liket uses for the facets inside the ggplot facet_wrap call*. This variable is a column called "Item" inside the myplot$data object.  As follows:

newplot <- myplot + facet_wrap(~factor(Item, levels = c("lev1", "lev2, "lev3")))

If you plot newplot you should have the desired ordering (at least worked for me).
