### ISSUE TITLE
Grouping histograms

### ISSUE THREAD

**Issue by esp112** [jbryer/likert#71]
jbryer,

Thanks for this package. It works nicely. I only have one issue I cannot deal with (I'm kind of new to r):

By default Likert items are plotted "by amount". I can change this and plot Likert items grouping them manually. The thing is that I added also a histogram, but it is ordered as the Likert items were in the first place, and Likert-histogram items do not match. I can find no way of rearranging histograms too...

Thanks in advance!

**Comment by jbryer** [comment]
Sorry, I am not entirely sure what you are asking. Can you provide a small
reproducible example, preferably with the data included in the package?

**Comment by esp112** [comment]
OK, I will explain it clearer and with your data:

I follow the steps in https://github.com/jbryer/likert/blob/master/demo/likert.R
until
l24 <- likert(items24)

and then I plot the following (attached as Plot1):
plot(l24,include.histogram = TRUE)
Everything seems OK so far. The items in the "y" axis in the two plots created are arranged by its mean value

If I plot afterward (attached as Plot2):
plot(l24, ordered=FALSE, group.order=names(items24),include.histogram=TRUE)

The plot is produced but the items in the histograms and the quartiles do not correspond to pairing obtained in the previous plot. For example, the category "I like to express my opinions about books I have read" contains 65497 answers according to the histogram in Plot1, but 65389 answers according to Plot2. On the contrary, the 65497 answers have been assigned to another item in Plot2.

![plot1](https://user-images.githubusercontent.com/30394826/28522894-32d5a736-707a-11e7-9543-2a1d43e9897c.png)
![plot2](https://user-images.githubusercontent.com/30394826/28522896-365e9818-707a-11e7-8849-1f60f7cf2775.png)
