### ISSUE TITLE
Change axis/legend font size in Likert graph when include.histogram=T

### ISSUE THREAD

**Issue by DevMui** [jbryer/likert#72]
I checked #66 to change axis/legend font size, which worked well with `include.histogram=F`. But it did not work when I turned the option on.

It would be nice if `plot.likert` function takes `font_size` as an option so that it can affect both graphs.

**Comment by jbryer** [comment]
Given the way the two plots are combined I don't think this will be possible. I would like to switch from the gridExtra package to patchwork package once patchwork is released to CRAN.
