### ISSUE TITLE
lickert package unavailable for R 3.4.2.

### ISSUE THREAD

**Issue by JedStephens** [jbryer/likert#77]
The lickert package from CRAN states that it is unavailable for R 3.4.2. 

Using the following:
install.packages("lickert")

Output
Installing package into ‘C:/Users/****/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘lickert’ is not available (for R version 3.4.2)

**Comment by jbryer** [comment]
You have a misspelling in the install.packages command.
