### ISSUE TITLE
Change font of percentage labels on the plot

### ISSUE THREAD

**Issue by alex4546** [jbryer/likert#78]
Hey altogether,
could anyone please help me out and tell me how I can change the font of the percentage labels on the plot (into Times New Roman)? I did change the axis labels via theme function but I couldn't find a solution for the percentage labels unfortunately. In addition I would like to squeeze the legend into one row. Any tips on that?

Best regards
Alex

**Comment by jbryer** [comment]
Using this will put the legend at the top: `theme(legend.position="top")` Change top to bottom for one row at the bottom. You should also be able to change the fonts with the theme option.
