### ISSUE TITLE
heatmap axis legends reordered alphabetically when moving to top 

### ISSUE THREAD

**Issue by verajosemanuel** [jbryer/likert#79]
reproducible example with demo plot:

`plot(l29, type='heat') + ggtitle(title)`

moving axis labels to top:

`plot(l29, type='heat') + ggtitle(title)  + scale_y_discrete(position = "top") `

columns are shuffled (I suppose Alphabetical order) 

Notice Mean (SD) in the middle of heatmap.

how can I preserve order?

![disorder](https://user-images.githubusercontent.com/15836677/32374542-7d0daf1e-c09e-11e7-9e28-bc82d9101d2b.png)

**Comment by jbryer** [comment]
By overriding the y scale, the limits are not preserved. That is, you need to specify the limits parameter to the scale_y_discrete call: scale_y_discrete(limits=c('Mean (SD)', names(likert$results)[2:ncol(likert$results)]) )

Alternatively, use the `theme(legend.position="top")` function instead.
