### ISSUE TITLE
Problems with <NA> values and grouping

### ISSUE THREAD

**Issue by ToxicDragon** [jbryer/likert#82]
There is a problem when plotting grouped likert data that inicludes \<NA\> values:
> plot(Q1Q3DataLikert2likert)
Error in `$<-.data.frame`(`*tmp*`, "low", value = c(14.2857142857143,  : 
  replacement has 20 rows, data has 10

Without the \<NA\>s in the dataset, I do not experience the problem.

See the following data for the complete and reproducable example:

Suppose the following dataset including \<NA\>s
> str(Q1Q3DataLikert2)
'data.frame':	25 obs. of  11 variables:
 $ Q1Sub1 : int  4 4 5 3 2 3 4 5 3 3 ...
 $ Q1Sub2 : int  4 5 2 2 3 2 NA 3 3 3 ...
 $ Q1Sub3 : int  2 2 2 2 1 4 NA 2 2 4 ...
 $ Q1Sub4 : int  5 4 3 5 5 3 5 4 4 4 ...
 $ Q1Sub5 : int  4 5 4 4 3 4 4 3 5 5 ...
 $ Q1Sub6 : int  4 5 4 4 5 5 5 4 5 3 ...
 $ Q1Sub7 : int  5 5 2 3 5 4 4 2 5 4 ...
 $ Q1Sub8 : int  3 4 2 5 5 4 4 4 5 2 ...
 $ Q1Sub9 : int  4 2 1 2 4 2 4 2 3 2 ...
 $ Q1Sub10: int  4 4 3 5 3 4 5 2 4 3 ...
 $ Q3     : Factor w/ 2 levels "Yes","No": 1 1 1 1 1 1 NA NA 1 2 ...

Add levels

> levels = c("Unimportant", "Rather unimportant", "Neutral", "Rather important", "Important")

> for(i in 1:(ncol(Q1Q3DataLikert2)-1)) {
    Q1Q3DataLikert2[[i]] = likert::recode(Q1Q3DataLikert2[[i]], from=c(1, 2, 3, 4, 5), to=levels)
}

Add ordered factors:
> for(i in 1:(ncol(Q1Q3DataLikert2)-1)) {
    Q1Q3DataLikert2[[i]] = factor(Q1Q3DataLikert2[[i]], levels = levels, ordered = TRUE)
}

> str(Q1Q3DataLikert2)
'data.frame':	25 obs. of  11 variables:
 $ Q1Sub1 : Ord.factor w/ 5 levels "Unimportant"<..: 4 4 5 3 2 3 4 5 3 3 ...
 $ Q1Sub2 : Ord.factor w/ 5 levels "Unimportant"<..: 4 5 2 2 3 2 NA 3 3 3 ...
 $ Q1Sub3 : Ord.factor w/ 5 levels "Unimportant"<..: 2 2 2 2 1 4 NA 2 2 4 ...
 $ Q1Sub4 : Ord.factor w/ 5 levels "Unimportant"<..: 5 4 3 5 5 3 5 4 4 4 ...
 $ Q1Sub5 : Ord.factor w/ 5 levels "Unimportant"<..: 4 5 4 4 3 4 4 3 5 5 ...
 $ Q1Sub6 : Ord.factor w/ 5 levels "Unimportant"<..: 4 5 4 4 5 5 5 4 5 3 ...
 $ Q1Sub7 : Ord.factor w/ 5 levels "Unimportant"<..: 5 5 2 3 5 4 4 2 5 4 ...
 $ Q1Sub8 : Ord.factor w/ 5 levels "Unimportant"<..: 3 4 2 5 5 4 4 4 5 2 ...
 $ Q1Sub9 : Ord.factor w/ 5 levels "Unimportant"<..: 4 2 1 2 4 2 4 2 3 2 ...
 $ Q1Sub10: Ord.factor w/ 5 levels "Unimportant"<..: 4 4 3 5 3 4 5 2 4 3 ...
 $ Q3     : Factor w/ 2 levels "Yes","No": 1 1 1 1 1 1 NA NA 1 2 ...

> summary(Q1Q3DataLikert2)
                Q1Sub1                  Q1Sub2                  Q1Sub3                 Q1Sub4                  Q1Sub5  
 Unimportant       : 0   Unimportant       : 1   Unimportant       :3   Unimportant       : 1   Unimportant       : 0  
 Rather unimportant: 3   Rather unimportant: 6   Rather unimportant:8   Rather unimportant: 1   Rather unimportant: 1  
 Neutral           :10   Neutral           :11   Neutral           :5   Neutral           : 5   Neutral           : 5  
 Rather important  : 7   Rather important  : 5   Rather important  :3   Rather important  :10   Rather important  : 9  
 Important         : 5   Important         : 1   Important         :4   Important         : 8   Important         :10  
                         NA's              : 1   NA's              :2                                                  
                Q1Sub6                  Q1Sub7                 Q1Sub8                 Q1Sub9                Q1Sub10  
 Unimportant       : 0   Unimportant       :0   Unimportant       :1   Unimportant       :4   Unimportant       : 2  
 Rather unimportant: 1   Rather unimportant:6   Rather unimportant:3   Rather unimportant:6   Rather unimportant: 3  
 Neutral           : 4   Neutral           :3   Neutral           :9   Neutral           :5   Neutral           : 5  
 Rather important  :10   Rather important  :9   Rather important  :6   Rather important  :8   Rather important  :10  
 Important         : 9   Important         :7   Important         :5   Important         :2   Important         : 5  
 NA's              : 1                          NA's              :1                                                 
    Q3    
 Yes :14  
 No  : 7  
 NA's: 4

Calculating likert:
> Q1Q3DataLikert2likert <- likert::likert(Q1Q3DataLikert2[, c(1:(ncol(Q1Q3DataLikert2)-1))], grouping = Q1Q3DataLikert2$Q3)
> Q1Q3DataLikert2likert
   Group    Item Unimportant Rather unimportant  Neutral Rather important Important
1    Yes  Q1Sub1    0.000000          14.285714 42.85714         28.57143 14.285714
2    Yes  Q1Sub2    0.000000          35.714286 35.71429         21.42857  7.142857
3    Yes  Q1Sub3   15.384615          38.461538 15.38462         15.38462 15.384615
4    Yes  Q1Sub4    7.142857           7.142857 21.42857         14.28571 50.000000
5    Yes  Q1Sub5    0.000000           7.142857 14.28571         50.00000 28.571429
6    Yes  Q1Sub6    0.000000           7.142857 14.28571         42.85714 35.714286
7    Yes  Q1Sub7    0.000000          35.714286 14.28571         14.28571 35.714286
8    Yes  Q1Sub8    7.142857           7.142857 42.85714         14.28571 28.571429
9    Yes  Q1Sub9   21.428571          28.571429 21.42857         28.57143  0.000000
10   Yes Q1Sub10   14.285714           0.000000 28.57143         42.85714 14.285714
11    No  Q1Sub1    0.000000          14.285714 57.14286         28.57143  0.000000
12    No  Q1Sub2    0.000000          14.285714 71.42857         14.28571  0.000000
13    No  Q1Sub3    0.000000          28.571429 28.57143         14.28571 28.571429
14    No  Q1Sub4    0.000000           0.000000 14.28571         85.71429  0.000000
15    No  Q1Sub5    0.000000           0.000000 28.57143         14.28571 57.142857
16    No  Q1Sub6    0.000000           0.000000 33.33333         33.33333 33.333333
17    No  Q1Sub7    0.000000           0.000000  0.00000         85.71429 14.285714
18    No  Q1Sub8    0.000000          33.333333 16.66667         33.33333 16.666667
19    No  Q1Sub9   14.285714          14.285714 28.57143         14.28571 28.571429
20    No Q1Sub10    0.000000          28.571429 14.28571         42.85714 14.285714
21  \<NA\>  Q1Sub1    0.000000           0.000000  0.00000          0.00000  0.000000
22  \<NA\>  Q1Sub2    0.000000           0.000000  0.00000          0.00000  0.000000
23  \<NA\>  Q1Sub3    0.000000           0.000000  0.00000          0.00000  0.000000
24  \<NA\>  Q1Sub4    0.000000           0.000000  0.00000          0.00000  0.000000
25  \<NA\>  Q1Sub5    0.000000           0.000000  0.00000          0.00000  0.000000
26  \<NA\>  Q1Sub6    0.000000           0.000000  0.00000          0.00000  0.000000
27  \<NA\>  Q1Sub7    0.000000           0.000000  0.00000          0.00000  0.000000
28  \<NA\>  Q1Sub8    0.000000           0.000000  0.00000          0.00000  0.000000
29  \<NA\>  Q1Sub9    0.000000           0.000000  0.00000          0.00000  0.000000
30  \<NA\> Q1Sub10    0.000000           0.000000  0.00000          0.00000  0.000000

The problem is, when plotting the chart, I get the following error:
> plot(Q1Q3DataLikert2likert)
Error in `$<-.data.frame`(`*tmp*`, "low", value = c(14.2857142857143,  : 
  replacement has 20 rows, data has 10

When clearing the \<NA\>'s from the dataset, everything works as aspected, see:
> Q1Q3DataLikert2 <- na.omit(Q1Q3DataLikert2)
> str(Q1Q3DataLikert2)
'data.frame':	19 obs. of  11 variables:
 $ Q1Sub1 : Ord.factor w/ 5 levels "Unimportant"<..: 4 4 5 3 2 3 3 3 3 2 ...
 $ Q1Sub2 : Ord.factor w/ 5 levels "Unimportant"<..: 4 5 2 2 3 2 3 3 2 3 ...
 $ Q1Sub3 : Ord.factor w/ 5 levels "Unimportant"<..: 2 2 2 2 1 4 2 4 3 1 ...
 $ Q1Sub4 : Ord.factor w/ 5 levels "Unimportant"<..: 5 4 3 5 5 3 4 4 1 2 ...
 $ Q1Sub5 : Ord.factor w/ 5 levels "Unimportant"<..: 4 5 4 4 3 4 5 5 2 4 ...
 $ Q1Sub6 : Ord.factor w/ 5 levels "Unimportant"<..: 4 5 4 4 5 5 5 3 2 4 ...
 $ Q1Sub7 : Ord.factor w/ 5 levels "Unimportant"<..: 5 5 2 3 5 4 5 4 2 2 ...
 $ Q1Sub8 : Ord.factor w/ 5 levels "Unimportant"<..: 3 4 2 5 5 4 5 2 3 3 ...
 $ Q1Sub9 : Ord.factor w/ 5 levels "Unimportant"<..: 4 2 1 2 4 2 3 2 1 3 ...
 $ Q1Sub10: Ord.factor w/ 5 levels "Unimportant"<..: 4 4 3 5 3 4 4 3 1 4 ...
 $ Q3     : Factor w/ 2 levels "Yes","No": 1 1 1 1 1 1 1 2 1 1 ...

> Q1Q3DataLikert2likert <- likert::likert(Q1Q3DataLikert2[, c(1:(ncol(Q1Q3DataLikert2)-1))], grouping = Q1Q3DataLikert2$Q3)
> Q1Q3DataLikert2likert
   Group    Item Unimportant Rather unimportant   Neutral Rather important Important
1    Yes  Q1Sub1    0.000000          15.384615 38.461538         30.76923 15.384615
2    Yes  Q1Sub2    0.000000          38.461538 30.769231         23.07692  7.692308
3    Yes  Q1Sub3   15.384615          38.461538 15.384615         15.38462 15.384615
4    Yes  Q1Sub4    7.692308           7.692308 23.076923         15.38462 46.153846
5    Yes  Q1Sub5    0.000000           7.692308 15.384615         46.15385 30.769231
6    Yes  Q1Sub6    0.000000           7.692308  7.692308         46.15385 38.461538
7    Yes  Q1Sub7    0.000000          38.461538  7.692308         15.38462 38.461538
8    Yes  Q1Sub8    7.692308           7.692308 38.461538         15.38462 30.769231
9    Yes  Q1Sub9   15.384615          30.769231 23.076923         30.76923  0.000000
10   Yes Q1Sub10   15.384615           0.000000 23.076923         46.15385 15.384615
11    No  Q1Sub1    0.000000          16.666667 50.000000         33.33333  0.000000
12    No  Q1Sub2    0.000000          16.666667 83.333333          0.00000  0.000000
13    No  Q1Sub3    0.000000          16.666667 33.333333         16.66667 33.333333
14    No  Q1Sub4    0.000000           0.000000 16.666667         83.33333  0.000000
15    No  Q1Sub5    0.000000           0.000000 33.333333         16.66667 50.000000
16    No  Q1Sub6    0.000000           0.000000 33.333333         33.33333 33.333333
17    No  Q1Sub7    0.000000           0.000000  0.000000         83.33333 16.666667
18    No  Q1Sub8    0.000000          33.333333 16.666667         33.33333 16.666667
19    No  Q1Sub9   16.666667          16.666667 33.333333         16.66667 16.666667
20    No Q1Sub10    0.000000          33.333333 16.666667         33.33333 16.666667

Afterwards, plotting works fine, but I do not have my missing values present (in calculation and histogram)...
> plot(Q1Q3DataLikert2likert, centered = FALSE, include.histogram = TRUE)
![rplot](https://user-images.githubusercontent.com/3375142/33525520-6165ccb0-d831-11e7-841f-87ed859c2db6.png)

Is there a way of having the missing values included?

**Comment by JamesBudge** [comment]
I am having the same issue. Did you ever find a work around?

**Comment by jbryer** [comment]
This is a known issue. You should handle missing values in the grouping
variable before calling likert. Future version will provide a better error
message.

**Comment by jbryer** [comment]
I have now added a check for missing values in the grouping variable and will through an error with a more meaningful message.

**Comment by RaimundK** [comment]
4 years later the same issue persists ...
