### ISSUE TITLE
Error: All items (columns) must have the same number of levels

### ISSUE THREAD

**Issue by srowelluf** [jbryer/likert#83]
I'm getting the error "All items (columns) must have the same number of levels.

I see previously, you told someone that it may be because a level isn't being used for an item - so I created a simply short data set where I made sure each level was used.
Testing_LKT_Pkg: 
Div     Q1     Q2     Q3
  <chr> <fctr> <fctr> <fctr>
1   LAK    Yes    Yes     No
2   MIA     No    Yes     No
3   JAX    Yes     No     No
4   LAK    Yes    Yes    Yes
5   CLT    Yes    Yes    Yes

With the levels:
> levels(Testing_LKT_Pkg$Q1)
[1] "Yes"   "No"    "Maybe"
> levels(Testing_LKT_Pkg$Q2)
[1] "Yes"   "No"    "Maybe"
> levels(Testing_LKT_Pkg$Q3)
[1] "Yes"   "No"    "Maybe"
I modeled my code, after your sample code:

items2 <- Testing_LKT_Pkg[, substr(names(Testing_LKT_Pkg), 1,1) == 'Q']
LKT2 <- likert(items2)
summary(LKT2)
plot(LKT2)

This creates the following tibble:
items2:

 A tibble: 6 x 3
      Q1     Q2     Q3
  <fctr> <fctr> <fctr>
1    Yes    Yes     No
2     No    Yes     No
3    Yes     No     No
4    Yes    Yes    Yes
5    Yes    Yes    Yes
6  Maybe  Maybe  Maybe

But it kicks out the following errror:
Error in likert(items2) : 
  All items (columns) must have the same number of levels

I also ran the code to test that all three items were factors with 3 levels.
> sapply(items2, class) #Verify that all the columns are indeed factors
      Q1       Q2       Q3 
"factor" "factor" "factor" 
> sapply(items2, function(x) { length(levels(x)) } ) # The number of levels in each factor
Q1 Q2 Q3 
 3  3  3

**Comment by jbryer** [comment]
Two things. First, tibbles are not supported. You will need to convert them
to plain data frames using the as.data.frame function.

Second, you should recode your columns as factors explicitly. This demo has
code to show you how to do that:
https://github.com/jbryer/likert/blob/master/demo/UnusedLevels.R

**Comment by DonnaVakalis** [comment]
I have a similar unresolved problem: 

I have a dataframe which is a single factor column. 

I coded it explicitly with levels and labels... i.e.,
df$ThermalComfort <-factor(df$ThermalComfort, levels = c(1,2,3,4),  labels = c("Too Cold","Just Right","Too Warm","Don't know"),ordered = TRUE)

And when I call likert(df)  I'm still getting the error "All items (columns) must have the same number of levels."

Here are the first few entries of the dataframe (note that "Too Cold" is an unused level, but the number of levels of the factor is still 4; and removing that level explicitly from the levels and labels doesn't prevent the error). 

ThermalComfort
<ord>
Too Warm				
Too Warm				
Just Right				
Too Warm				
Don't know				
Too Warm				
Too Warm				
Too Warm				
Just Right				
Too Warm

**Comment by jbryer** [comment]
I assume you are doing this:

```
> test <- likert(items24[,1])
Error in likert(items24[, 1]) : 
  The items parameter must be a data frame. If trying to subset a data frame to analyze only one column, try: items=mydf[,1, drop=FALSE].
```

The answer is in the error message. If you don't see that, let me know as that is a bug. The problem is when you subset a data frame either as `df$column` or `df[,1]` the result is a vector, not a data frame. The `likert` function expects a `data.frame`, add the `drop = FALSE` parameter. In your example, this should work:

```
likert(df[,'ThermalComfort', drop = FALSE])
```

**Comment by DonnaVakalis** [comment]
Hi @jbryer thank you sooo much for responding.  Here is the str() for the single-column dataframe:

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	54 obs. of  1 variable:
 $ ThermalComfort: Ord.factor w/ 4 levels "Too Cold"<"Just Right"<..: 3 3 2 3 4 3 3 3 2 3 ...

And I still get the error, i.e.,
"Error in likert(df) : All items (columns) must have the same number of levels"

I'm flummoxed.

**Comment by jbryer** [comment]
Ok, the problem is with Tibbles. This is proving to be a big problem. This
can be fixed by calling `as.data.frame` before calling `likert`.

For some more background, `is.data.frame` returns true for a `tibble`. This
makes sense if you look at the results of `class(df)`. However, even though
a `tibble` is suppose to behave like any other `data.frame`, it doesn't.
