### ISSUE TITLE
How to Change the Legend Text? How can I change the Item ordering?

### ISSUE THREAD

**Issue by tousifeshan** [jbryer/likert#90]
Hi,
The Legend text is displaying Response. I want to change that to something else. How can I do that?

Moreover, whenever I am plotting it changes the default ordering. Instead the items are being sorted as factors. My Column names are Name, Birthday, Age,Picture. I want the stacked bar charts to be shown in the same order. But the plot is drawn in this order Age, Birthday, Name,  and Picture. 

How can we user likert.options?

**Comment by janinekhuc** [comment]
The answers below are applicable to the likert bar plots:
_To change the legend label_, try to add `theme(legend.title=element_text('new legend title'))` to your existing plot. So if you save p as your plot it would be 
 `p + theme(legend.title=element_text('new legend title'))`

_To keep the order as in your data frame_, add `ordered = FALSE, group.order = names(df)` to your plot. 
So if df would be your dataframe and likert_object the object you receive after likert(), it would look like following
`plot(likert_object, center = 3, col=myColor, ordered = FALSE, group.order = names(df)) `

Does that answer your questions?

**Comment by jbryer** [comment]
Thanks @janinekhuc

**Comment by nancythule2309** [comment]
Hi @mgronas-werring, this works for me.
p + guides(fill=guide_legend("new legend title"))
