### ISSUE TITLE
Cannot include.histogram() and add ggtitle()

### ISSUE THREAD

**Issue by janinekhuc** [jbryer/likert#91]
I can add title/ histograms separately with no issue.
But if I try to add a title and plot a histogram `plot(l24,include.histogram = TRUE) + ggtitle('test')` I get the following error:

```
Error in plot(l24, include.histogram = TRUE) + ggtitle("test") : 
  non-numeric argument to binary operator
```
Any clue what this could be due to?

**Comment by jbryer** [comment]
Typically the plot function returns a ggplot2 expression, except when histograms are included. To combine multiple plot types the gridExtra package is used. I may switch to patchwork once it has been released to CRAN. Either way, this will not be supported.
